AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  TargetRubyVersion: 2.4

  Exclude:
    - '**/*.sh'
    - '**/*.bash'
    - '**/*.yml'
    - '**/*.txt'
    - '**/*.md'
    - spec/*.opts
    - tmp/**/*
    - log/**/*
    - Rakefile
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false
